[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
aipool_auction = "Auctn5jG7vS8SAH1LWvyKF1vWJbMFzXeMJjBQGdiWUZu"

[registry]
url = ""

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/iddd.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
